pipeline {
    agent any
    stages{
        stage("SCM Checkout"){
            steps{
                echo "Cloning the repo"
            }
        }
        stage("Build"){
            steps{
                echo "Build stage"
            }
        }
        stage("Test"){
            steps{
                echo "Test stage"
            }
        }
    }
}
